# Generated by Django 5.2.5 on 2025-09-03 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_payment_order_payment_product_purchaseproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
